[2024-03-10T20:28:13.797+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: EnergyWarehouse.load_conso_energy_region manual__2024-03-10T20:19:52.813168+00:00 [queued]>
[2024-03-10T20:28:13.956+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: EnergyWarehouse.load_conso_energy_region manual__2024-03-10T20:19:52.813168+00:00 [queued]>
[2024-03-10T20:28:13.976+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2024-03-10T20:28:17.676+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): load_conso_energy_region> on 2024-03-10 20:19:52.813168+00:00
[2024-03-10T20:28:17.943+0000] {standard_task_runner.py:57} INFO - Started process 1665 to run task
[2024-03-10T20:28:18.097+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'EnergyWarehouse', 'load_conso_energy_region', 'manual__2024-03-10T20:19:52.813168+00:00', '--job-id', '881', '--raw', '--subdir', 'DAGS_FOLDER/***-to-bigquery-dag/***_to_bigquerry_dag.py', '--cfg-path', '/tmp/tmppm4cogwy']
[2024-03-10T20:28:18.129+0000] {standard_task_runner.py:85} INFO - Job 881: Subtask load_conso_energy_region
[2024-03-10T20:28:19.016+0000] {task_command.py:410} INFO - Running <TaskInstance: EnergyWarehouse.load_conso_energy_region manual__2024-03-10T20:19:52.813168+00:00 [running]> on host 952b3f8a1a94
[2024-03-10T20:28:23.514+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mbaye SENE' AIRFLOW_CTX_DAG_ID='EnergyWarehouse' AIRFLOW_CTX_TASK_ID='load_conso_energy_region' AIRFLOW_CTX_EXECUTION_DATE='2024-03-10T20:19:52.813168+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-10T20:19:52.813168+00:00'
[2024-03-10T20:28:23.667+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/operators/python.py:198: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version.


  return self.python_callable(*self.op_args, **self.op_kwargs)

[2024-03-10T20:28:33.249+0000] {python.py:183} INFO - Done. Returned value was: None
[2024-03-10T20:28:33.494+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=EnergyWarehouse, task_id=load_conso_energy_region, execution_date=20240310T201952, start_date=20240310T202813, end_date=20240310T202833
[2024-03-10T20:28:34.695+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2024-03-10T20:28:38.012+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
