[2023-06-14T13:15:50.385+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_psql_send_s3.send_csv_s3 manual__2023-06-14T13:15:44.018525+00:00 [queued]>
[2023-06-14T13:15:50.401+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_psql_send_s3.send_csv_s3 manual__2023-06-14T13:15:44.018525+00:00 [queued]>
[2023-06-14T13:15:50.402+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-14T13:15:50.424+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): send_csv_s3> on 2023-06-14 13:15:44.018525+00:00
[2023-06-14T13:15:50.436+0000] {standard_task_runner.py:57} INFO - Started process 2584 to run task
[2023-06-14T13:15:50.443+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'get_psql_send_s3', 'send_csv_s3', 'manual__2023-06-14T13:15:44.018525+00:00', '--job-id', '1511', '--raw', '--subdir', 'DAGS_FOLDER/end_to_end_pipeline_***.py', '--cfg-path', '/tmp/tmpgy_j33co']
[2023-06-14T13:15:50.447+0000] {standard_task_runner.py:85} INFO - Job 1511: Subtask send_csv_s3
[2023-06-14T13:15:50.513+0000] {task_command.py:410} INFO - Running <TaskInstance: get_psql_send_s3.send_csv_s3 manual__2023-06-14T13:15:44.018525+00:00 [running]> on host cd01a659cc96
[2023-06-14T13:15:50.616+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='get_psql_send_s3' AIRFLOW_CTX_TASK_ID='send_csv_s3' AIRFLOW_CTX_EXECUTION_DATE='2023-06-14T13:15:44.018525+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-14T13:15:44.018525+00:00'
[2023-06-14T13:15:52.894+0000] {python.py:183} INFO - Done. Returned value was: None
[2023-06-14T13:15:52.915+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=get_psql_send_s3, task_id=send_csv_s3, execution_date=20230614T131544, start_date=20230614T131550, end_date=20230614T131552
[2023-06-14T13:15:52.962+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-06-14T13:15:52.988+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
